version: '2'

services:
    application:
        container_name: per_laravel_app_application
        image: debian
        volumes:
            - ./:/var/www/laravel
    workspace:
        container_name: per_laravel_app_workspace
        restart: always
        build:
          context: ./_docker/workspace
        volumes_from:
            - application
        tty: true
    php-fpm:
        container_name: per_laravel_app_php-fpm
        restart: always
        image: kenini1805/laravel-php-fpm
        volumes_from:
            - application
        expose:
            - "9000"
        links:
            - workspace
    nginx:
        container_name: per_laravel_app_nginx
        restart: always
        image: framgia/laravel-nginx
        volumes_from:
            - data
            - logs
            - application
        ports:
            - "80:80"
        links:
            - php-fpm
    data:
        container_name: per_laravel_app_data
        image: debian
        volumes:
            - .docker/mysql:/var/lib/mysql
            - .docker/data:/data
    data_test:
        container_name: per_laravel_app_data_test
        image: debian
        volumes:
            - .docker/mysql_test:/var/lib/mysql
            - .docker/data_test:/data
    logs:
        container_name: per_laravel_app_logs
        image: debian
        volumes:
            - .docker/logs/nginx:/var/log/nginx
            - .docker/logs/mongodb:/var/log/mongodb
    mysql:
        container_name: per_laravel_app_mysql
        restart: always
        image: mysql:5.7
        volumes_from:
            - data
            - logs
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: per_laravel_app
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
    mysql_test:
        container_name: per_laravel_app_mysql_test
        restart: always
        image: mysql:5.7
        volumes_from:
            - data_test
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: per_laravel_app_test
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
    redis:
        container_name: per_laravel_app_redis
        restart: always
        image: redis
        expose:
            - "6379"
        volumes_from:
            - data
